# Generated by Django 2.1.1 on 2018-09-10 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('ip', models.CharField(max_length=20)),
                ('pub_date', models.DateTimeField(verbose_name='date posted')),
            ],
        ),
    ]
